create database proy_polleria
use proy_polleria
/*TABLA INICIO*/
create table inicio
(
id_inicio int identity(1,1) not null,
usuario varchar(30) not null,
contrasena varchar(30) not null
)
insert into inicio values ('admin','123')

select * from inicio

/*TABLA DE REGISTRO DE USUARIO*/

CREATE TABLE USUARIOS(
	IDUSUARIO INT IDENTITY NOT NULL,
	USUARIO VARCHAR(40),
	NOMBRE VARCHAR(40) ,
	APELLIDO VARCHAR(40) ,
	FECHA_NAC DATE,
	SEXO CHAR(1) ,
	DIRECCION VARCHAR(50),
	CORREO VARCHAR(40),
	CONTRASEÑA VARCHAR(40),
	FECHA_ACC DATETIME,
	IDTIPOUSU INT,
	CONSTRAINT PK_USUARIOS PRIMARY KEY(IDUSUARIO),
	--CONSTRAINT FK_TIPOUSUARIO FOREIGN KEY(IDTIPOUSU) REFERENCES TIPOUSUARIO(IDTIPOUSU),
)
INSERT INTO USUARIOS (USUARIO, CONTRASEÑA, IDTIPOUSU) VALUES('LEO','leo',1)