/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class Cambiar_contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Cambiar_contraseña
     */
    public Cambiar_contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiar_contraseña = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        logo_pequeño = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        candado1 = new javax.swing.JLabel();
        barra3 = new javax.swing.JLabel();
        visible = new javax.swing.JButton();
        candado2 = new javax.swing.JLabel();
        visible1 = new javax.swing.JButton();
        barra4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cambiar_contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulocambiarcontrasseña.png"))); // NOI18N
        getContentPane().add(cambiar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 380, 40));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Back.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Backsegundo.png"))); // NOI18N
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 40));

        logo_pequeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_BG.png"))); // NOI18N
        getContentPane().add(logo_pequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 90, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -4, 640, 80));

        candado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Candado.png"))); // NOI18N
        getContentPane().add(candado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 224, 20, 30));

        barra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 257, 390, 10));

        visible.setForeground(new java.awt.Color(255, 255, 255));
        visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Visible.jpg"))); // NOI18N
        visible.setBorder(null);
        visible.setBorderPainted(false);
        visible.setContentAreaFilled(false);
        visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleActionPerformed(evt);
            }
        });
        getContentPane().add(visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(11010, 225, 30, 20));

        candado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Candado.png"))); // NOI18N
        getContentPane().add(candado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 309, 20, 30));

        visible1.setForeground(new java.awt.Color(255, 255, 255));
        visible1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Visible.jpg"))); // NOI18N
        visible1.setBorder(null);
        visible1.setBorderPainted(false);
        visible1.setContentAreaFilled(false);
        visible1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visible1ActionPerformed(evt);
            }
        });
        getContentPane().add(visible1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 30, 20));

        barra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 340, 390, 10));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoIzquierdo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleActionPerformed
        visible.setVisible(false);
        
    }//GEN-LAST:event_visibleActionPerformed

    private void visible1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visible1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visible1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambiar_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiar_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel barra3;
    private javax.swing.JLabel barra4;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel cambiar_contraseña;
    private javax.swing.JLabel candado1;
    private javax.swing.JLabel candado2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo_pequeño;
    private javax.swing.JButton visible;
    private javax.swing.JButton visible1;
    // End of variables declaration//GEN-END:variables
}
