/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class Registro_de_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Registro_de_usuario
     */
    public Registro_de_usuario() {
        initComponents();
        TextPrompt usuario=new TextPrompt("Ingrese su Nombre de Usuario",tf_usuario);
        TextPrompt nombre=new TextPrompt("Ingrese su Nombre", tf_nombre);
        TextPrompt apellido=new TextPrompt("Ingrese su Apellido", tf_apellido);
        TextPrompt correo=new TextPrompt("Ingrese su Correo Electronico", tf_correo);
        TextPrompt contra=new TextPrompt("Ingrese su contraseña", tf_contra);
        TextPrompt numCelular=new TextPrompt("Ingrese su Numero de Celular", tf_num_celular);
        this.setLocationRelativeTo(null); //CENTRANDO EL JFRAME
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        logo_pequeño = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();
        candado = new javax.swing.JLabel();
        barra2 = new javax.swing.JLabel();
        visible = new javax.swing.JButton();
        noVisible = new javax.swing.JButton();
        candado1 = new javax.swing.JLabel();
        barra3 = new javax.swing.JLabel();
        candado2 = new javax.swing.JLabel();
        barra4 = new javax.swing.JLabel();
        cumpleaños = new javax.swing.JLabel();
        barra5 = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        barra6 = new javax.swing.JLabel();
        correo1 = new javax.swing.JLabel();
        barra7 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        olvidemicontraseña = new javax.swing.JLabel();
        tf_num_celular = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JPasswordField();
        jdc_calendario = new com.toedter.calendar.JDateChooser();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Back.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Backsegundo.png"))); // NOI18N
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 40, 40));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 19, 330, -1));

        logo_pequeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_BG.png"))); // NOI18N
        getContentPane().add(logo_pequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 4, 90, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -3, 640, 80));

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Usuario.png"))); // NOI18N
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 126, 20, 30));

        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 150, 370, 10));

        candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Profile.png"))); // NOI18N
        getContentPane().add(candado, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 310, 30, -1));

        barra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 396, 420, 10));

        visible.setForeground(new java.awt.Color(255, 255, 255));
        visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Visible.jpg"))); // NOI18N
        visible.setBorder(null);
        visible.setBorderPainted(false);
        visible.setContentAreaFilled(false);
        visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibleActionPerformed(evt);
            }
        });
        getContentPane().add(visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(1112, 186, 30, 20));

        noVisible.setForeground(new java.awt.Color(255, 255, 255));
        noVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/noVisible.png"))); // NOI18N
        noVisible.setBorder(null);
        noVisible.setBorderPainted(false);
        noVisible.setContentAreaFilled(false);
        noVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noVisibleActionPerformed(evt);
            }
        });
        getContentPane().add(noVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(1112, 186, 30, 20));

        candado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Candado.png"))); // NOI18N
        getContentPane().add(candado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 180, 20, 30));

        barra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 204, 390, 10));

        candado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Profile.png"))); // NOI18N
        getContentPane().add(candado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 253, 30, -1));

        barra4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 272, 400, 10));

        cumpleaños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Cumpleaños.png"))); // NOI18N
        getContentPane().add(cumpleaños, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 370, 20, 30));

        barra5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 330, 410, 10));

        celular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Celular.png"))); // NOI18N
        getContentPane().add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 490, 20, 30));

        barra6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 515, 390, 10));

        correo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG_Correo.png"))); // NOI18N
        getContentPane().add(correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 430, 30, 30));

        barra7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_grande.png"))); // NOI18N
        getContentPane().add(barra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 452, 410, 10));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Aceptar.png"))); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Aceptarsegundo.png"))); // NOI18N
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 624, 340, 50));

        olvidemicontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        olvidemicontraseña.setForeground(new java.awt.Color(168, 12, 17));
        olvidemicontraseña.setText("Acepta los términos y condiciones");
        olvidemicontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvidemicontraseñaMouseClicked(evt);
            }
        });
        getContentPane().add(olvidemicontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 574, 280, 20));

        tf_num_celular.setBorder(null);
        tf_num_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_num_celularActionPerformed(evt);
            }
        });
        getContentPane().add(tf_num_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 330, 30));

        tf_correo.setBorder(null);
        tf_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_correoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 340, 30));

        tf_apellido.setBorder(null);
        getContentPane().add(tf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 330, 30));

        tf_nombre.setBorder(null);
        getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 320, 30));

        tf_usuario.setBorder(null);
        getContentPane().add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 340, 30));

        tf_contra.setBorder(null);
        getContentPane().add(tf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 290, -1));

        jdc_calendario.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jdc_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 330, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoIzquierdo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibleActionPerformed
        visible.setVisible(false);
        noVisible.setVisible(true);
    }//GEN-LAST:event_visibleActionPerformed

    private void noVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noVisibleActionPerformed
        noVisible.setVisible(false);
        visible.setVisible(true);
    }//GEN-LAST:event_noVisibleActionPerformed

    private void olvidemicontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvidemicontraseñaMouseClicked

        /*A qui se colocara a donde se quiere mandar*/
    }//GEN-LAST:event_olvidemicontraseñaMouseClicked

    private void tf_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_correoActionPerformed

    private void tf_num_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_num_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_num_celularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_de_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel barra2;
    private javax.swing.JLabel barra3;
    private javax.swing.JLabel barra4;
    private javax.swing.JLabel barra5;
    private javax.swing.JLabel barra6;
    private javax.swing.JLabel barra7;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel candado;
    private javax.swing.JLabel candado1;
    private javax.swing.JLabel candado2;
    private javax.swing.JLabel celular;
    private javax.swing.JLabel correo1;
    private javax.swing.JLabel cumpleaños;
    private javax.swing.JLabel fondo;
    private com.toedter.calendar.JDateChooser jdc_calendario;
    private javax.swing.JLabel logo_pequeño;
    private javax.swing.JButton noVisible;
    private javax.swing.JLabel olvidemicontraseña;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JPasswordField tf_contra;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_num_celular;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton visible;
    // End of variables declaration//GEN-END:variables
}
