/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class Resumen_Diario extends javax.swing.JFrame {

    /**
     * Creates new form Resumen_Diario
     */
    public Resumen_Diario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        valido = new javax.swing.JLabel();
        fechadecreacion = new javax.swing.JLabel();
        utilizado = new javax.swing.JLabel();
        fechadeuso1 = new javax.swing.JLabel();
        fechadeuso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        valido1 = new javax.swing.JLabel();
        valido2 = new javax.swing.JLabel();
        valido3 = new javax.swing.JLabel();
        valido4 = new javax.swing.JLabel();
        valido5 = new javax.swing.JLabel();
        valido6 = new javax.swing.JLabel();
        valido7 = new javax.swing.JLabel();
        stock1 = new javax.swing.JLabel();
        stock2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        ResumenDiario = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnMinimisar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 30, 20));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Día:");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 30, 20));

        stock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock.setText("Meseros Totales:");
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 140, 30));

        descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descuento.setText("Patillos Totales:");
        jPanel1.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 130, 20));

        valido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 16.png"))); // NOI18N
        jPanel1.add(valido, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 60, 80, 80));

        fechadecreacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadecreacion.setText("Cocineros Totales:");
        jPanel1.add(fechadecreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, 20));

        utilizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        utilizado.setText("Insumos Gastados:");
        jPanel1.add(utilizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 160, 30));

        fechadeuso1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadeuso1.setText("por Cliente:");
        jPanel1.add(fechadeuso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 100, 20));

        fechadeuso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadeuso.setText("Gasto Promedio");
        jPanel1.add(fechadeuso, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 130, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1220, 460));

        valido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido1.setText("Total Clientes:");
        jPanel1.add(valido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 130, 20));

        valido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientes_azul.png"))); // NOI18N
        jPanel1.add(valido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 50, 130, 40));

        valido3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadro.png"))); // NOI18N
        jPanel1.add(valido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 20, 180, 220));

        valido4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingresos.png"))); // NOI18N
        jPanel1.add(valido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 50, 140, 40));

        valido5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 17.png"))); // NOI18N
        jPanel1.add(valido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 80, 80));

        valido6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Platillos_amarillo.png"))); // NOI18N
        jPanel1.add(valido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 180, 130, 40));

        valido7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 15.png"))); // NOI18N
        jPanel1.add(valido7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 70));

        stock1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock1.setText("Ingresos:");
        jPanel1.add(stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        stock2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock2.setText("Cargo:");
        jPanel1.add(stock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, 30));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, 650));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cerrar.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cerrarsegundo.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 40, 40));

        ResumenDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resumen_diario_titulo.png"))); // NOI18N
        getContentPane().add(ResumenDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 20, -1, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Back.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Backsegundo.png"))); // NOI18N
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 20, 40, 40));

        btnMinimisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Minimizar.png"))); // NOI18N
        btnMinimisar.setBorder(null);
        btnMinimisar.setBorderPainted(false);
        btnMinimisar.setContentAreaFilled(false);
        btnMinimisar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Minimizarsegundo.png"))); // NOI18N
        getContentPane().add(btnMinimisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1136, 20, 40, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG_grande.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resumen_Diario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResumenDiario;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimisar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel fechadecreacion;
    private javax.swing.JLabel fechadeuso;
    private javax.swing.JLabel fechadeuso1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel stock1;
    private javax.swing.JLabel stock2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel utilizado;
    private javax.swing.JLabel valido;
    private javax.swing.JLabel valido1;
    private javax.swing.JLabel valido2;
    private javax.swing.JLabel valido3;
    private javax.swing.JLabel valido4;
    private javax.swing.JLabel valido5;
    private javax.swing.JLabel valido6;
    private javax.swing.JLabel valido7;
    // End of variables declaration//GEN-END:variables
}
