package interfaces;


import interfaces.Menu_Principal;
import dao.TextPrompt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author David
 */
public class Resumen_Diario extends javax.swing.JFrame {

    /**
     * Creates new form Resumen_Diario
     */
    public Resumen_Diario() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt ID = new TextPrompt("010203040506070809", tf_id);//ID

        TextPrompt cargo = new TextPrompt("Cocinero", tf_cargo);//CARGO
        TextPrompt cocineroTotales = new TextPrompt("010203040506070809", tf_cocinerostotales);//COCINERO TOTALES
        TextPrompt gatopromedio = new TextPrompt("010203040506070809", tf_gastopromedioporcliente);//GATOPROMEDIO
        TextPrompt ingreso = new TextPrompt("", tf_ingreso);//INGRESO
        TextPrompt insumosgastados = new TextPrompt("010203040506070809", tf_insumosgastados);//INSUMOSGASTADOS
        TextPrompt meseros = new TextPrompt("010203040506070809", tf_meserostotales);//MESEROS
        TextPrompt patillo_total = new TextPrompt("010203040506070809", tf_patillostotales);//PLATILLO TOTALES
        TextPrompt total_cliente = new TextPrompt("010203040506070809", tf_totalcliente);//TOTAL CLIENTE
        /*dia*/
        TextPrompt ddDia = new TextPrompt(" " + " 10", dd_dia);
        TextPrompt mmDia = new TextPrompt(" " + " 10", mm_dia);
        TextPrompt yyDia = new TextPrompt(" " + " 2019", yy_dia);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dd_dia = new javax.swing.JTextField();
        RLSexo2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        mm_dia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        yy_dia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_ingreso = new javax.swing.JTextField();
        tf_cargo = new javax.swing.JTextField();
        tf_totalcliente = new javax.swing.JTextField();
        tf_patillostotales = new javax.swing.JTextField();
        tf_cocinerostotales = new javax.swing.JTextField();
        tf_meserostotales = new javax.swing.JTextField();
        tf_insumosgastados = new javax.swing.JTextField();
        tf_gastopromedioporcliente = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        valido = new javax.swing.JLabel();
        fechadecreacion = new javax.swing.JLabel();
        utilizado = new javax.swing.JLabel();
        fechadeuso1 = new javax.swing.JLabel();
        fechadeuso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        valido1 = new javax.swing.JLabel();
        valido2 = new javax.swing.JLabel();
        valido3 = new javax.swing.JLabel();
        valido4 = new javax.swing.JLabel();
        valido5 = new javax.swing.JLabel();
        valido6 = new javax.swing.JLabel();
        valido7 = new javax.swing.JLabel();
        stock1 = new javax.swing.JLabel();
        stock2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        ResumenDiario = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnMinimisar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 40, 20));

        dd_dia.setBorder(null);
        dd_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dd_diaActionPerformed(evt);
            }
        });
        jPanel1.add(dd_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 40, 30));

        RLSexo2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        RLSexo2.setForeground(new java.awt.Color(204, 0, 0));
        RLSexo2.setText("Día           Mes             Año");
        jPanel1.add(RLSexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 24));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 40, 20));

        mm_dia.setBorder(null);
        mm_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mm_diaActionPerformed(evt);
            }
        });
        jPanel1.add(mm_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 40, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 50, 20));

        yy_dia.setBorder(null);
        yy_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yy_diaActionPerformed(evt);
            }
        });
        jPanel1.add(yy_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 50, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 230, 10));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 455, 230, 10));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 507, 230, 10));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 230, 10));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 230, 10));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 453, 230, 10));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 508, 230, 10));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 230, 10));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Separador_negro.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 230, 10));

        tf_id.setBorder(null);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        jPanel1.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 290, 30));

        tf_ingreso.setBorder(null);
        tf_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ingresoActionPerformed(evt);
            }
        });
        jPanel1.add(tf_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 250, 20));

        tf_cargo.setBorder(null);
        tf_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cargoActionPerformed(evt);
            }
        });
        jPanel1.add(tf_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 240, 20));

        tf_totalcliente.setBorder(null);
        tf_totalcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalclienteActionPerformed(evt);
            }
        });
        jPanel1.add(tf_totalcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 250, 20));

        tf_patillostotales.setBorder(null);
        tf_patillostotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_patillostotalesActionPerformed(evt);
            }
        });
        jPanel1.add(tf_patillostotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 230, 30));

        tf_cocinerostotales.setBorder(null);
        tf_cocinerostotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cocinerostotalesActionPerformed(evt);
            }
        });
        jPanel1.add(tf_cocinerostotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 210, 30));

        tf_meserostotales.setBorder(null);
        tf_meserostotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_meserostotalesActionPerformed(evt);
            }
        });
        jPanel1.add(tf_meserostotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 240, 20));

        tf_insumosgastados.setBorder(null);
        tf_insumosgastados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_insumosgastadosActionPerformed(evt);
            }
        });
        jPanel1.add(tf_insumosgastados, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 250, 30));

        tf_gastopromedioporcliente.setBorder(null);
        tf_gastopromedioporcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_gastopromedioporclienteActionPerformed(evt);
            }
        });
        jPanel1.add(tf_gastopromedioporcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 240, 30));

        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 30, 20));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Día:");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 30, 20));

        stock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock.setText("Meseros Totales:");
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 140, 30));

        descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descuento.setText("Patillos Totales:");
        jPanel1.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 130, 20));

        valido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 16.png"))); // NOI18N
        jPanel1.add(valido, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 60, 80, 80));

        fechadecreacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadecreacion.setText("Cocineros Totales:");
        jPanel1.add(fechadecreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, 20));

        utilizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        utilizado.setText("Insumos Gastados:");
        jPanel1.add(utilizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 160, 30));

        fechadeuso1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadeuso1.setText("por Cliente:");
        jPanel1.add(fechadeuso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 100, 20));

        fechadeuso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechadeuso.setText("Gasto Promedio");
        jPanel1.add(fechadeuso, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 130, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 1220, 460));

        valido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido1.setText("Total Clientes:");
        jPanel1.add(valido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 130, 20));

        valido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientes_azul.png"))); // NOI18N
        jPanel1.add(valido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 50, 130, 40));

        valido3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuadro.png"))); // NOI18N
        jPanel1.add(valido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 20, 180, 220));

        valido4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingresos.png"))); // NOI18N
        jPanel1.add(valido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 50, 140, 40));

        valido5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 17.png"))); // NOI18N
        jPanel1.add(valido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 80, 80));

        valido6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Platillos_amarillo.png"))); // NOI18N
        jPanel1.add(valido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 180, 130, 40));

        valido7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valido7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 15.png"))); // NOI18N
        jPanel1.add(valido7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 70));

        stock1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock1.setText("Ingresos:");
        jPanel1.add(stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 90, 30));

        stock2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stock2.setText("Cargo:");
        jPanel1.add(stock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, 30));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1280, 650));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cerrar.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Cerrarsegundo.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 40, 40));

        ResumenDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resumen_diario_titulo.png"))); // NOI18N
        getContentPane().add(ResumenDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 20, -1, 30));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Back.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Backsegundo.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 20, 40, 40));

        btnMinimisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Minimizar.png"))); // NOI18N
        btnMinimisar.setBorder(null);
        btnMinimisar.setBorderPainted(false);
        btnMinimisar.setContentAreaFilled(false);
        btnMinimisar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Minimizarsegundo.png"))); // NOI18N
        btnMinimisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 40, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG_grande.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        //INGRESANDO EL BOTON DE CERRAR SESION
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ingresoActionPerformed

    private void tf_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cargoActionPerformed

    private void tf_totalclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalclienteActionPerformed

    private void tf_patillostotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_patillostotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_patillostotalesActionPerformed

    private void tf_cocinerostotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cocinerostotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cocinerostotalesActionPerformed

    private void tf_meserostotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_meserostotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_meserostotalesActionPerformed

    private void tf_insumosgastadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_insumosgastadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_insumosgastadosActionPerformed

    private void tf_gastopromedioporclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_gastopromedioporclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_gastopromedioporclienteActionPerformed

    private void btnMinimisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimisarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimisarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new Menu_Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void dd_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dd_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dd_diaActionPerformed

    private void mm_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mm_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mm_diaActionPerformed

    private void yy_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yy_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yy_diaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resumen_Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resumen_Diario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RLSexo2;
    private javax.swing.JLabel ResumenDiario;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimisar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField dd_dia;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel fechadecreacion;
    private javax.swing.JLabel fechadeuso;
    private javax.swing.JLabel fechadeuso1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mm_dia;
    private javax.swing.JLabel stock;
    private javax.swing.JLabel stock1;
    private javax.swing.JLabel stock2;
    private javax.swing.JTextField tf_cargo;
    private javax.swing.JTextField tf_cocinerostotales;
    private javax.swing.JTextField tf_gastopromedioporcliente;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_ingreso;
    private javax.swing.JTextField tf_insumosgastados;
    private javax.swing.JTextField tf_meserostotales;
    private javax.swing.JTextField tf_patillostotales;
    private javax.swing.JTextField tf_totalcliente;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel utilizado;
    private javax.swing.JLabel valido;
    private javax.swing.JLabel valido1;
    private javax.swing.JLabel valido2;
    private javax.swing.JLabel valido3;
    private javax.swing.JLabel valido4;
    private javax.swing.JLabel valido5;
    private javax.swing.JLabel valido6;
    private javax.swing.JLabel valido7;
    private javax.swing.JTextField yy_dia;
    // End of variables declaration//GEN-END:variables
}
